from fastapi import FastAPI, Depends, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from sqlmodel import Session, select
from database import create_db_and_tables, get_session
from models import Idea
import scraper

app = FastAPI(title="Business Idea Scraper API")

# Setup CORS to allow frontend connections
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # In production this should be restricted
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.on_event("startup")
def on_startup():
    create_db_and_tables()

@app.get("/ideas")
def get_ideas(status: str = "pending", session: Session = Depends(get_session)):
    statement = select(Idea).where(Idea.status == status).order_by(Idea.score.desc())
    results = session.exec(statement)
    return results.all()

@app.post("/ideas/{idea_id}/status")
def update_idea_status(idea_id: int, status: str, session: Session = Depends(get_session)):
    """Update idea status (approved, rejected, starred, pending)"""
    idea = session.get(Idea, idea_id)
    if not idea:
        raise HTTPException(status_code=404, detail="Idea not found")
    
    if status not in ["pending", "approved", "rejected", "starred"]:
        raise HTTPException(status_code=400, detail="Invalid status")
        
    idea.status = status
    session.add(idea)
    session.commit()
    session.refresh(idea)
    return idea

@app.post("/scrape")
async def trigger_scrape(background_tasks: BackgroundTasks, topic: str = None, session: Session = Depends(get_session)):
    """Trigger a manual scrape of sources. Optionally filter by topic."""
    background_tasks.add_task(scraper.run_all_scrapers, session, topic)
    msg = f"Scrape job started in the background"
    if topic:
        msg += f" for topic: {topic}"
    return {"message": msg}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)

@app.post("/random")
async def trigger_random(session: Session = Depends(get_session)):
    """Directly asks the AI to generate a random business idea and stores it."""
    from ai_processor import generate_random_idea
    import uuid
    evaluation = await generate_random_idea()
    
    if evaluation.get("is_idea", False):
        new_idea = Idea(
            title="AI Generated Random Idea",
            summary=evaluation.get("summary"),
            source_url=f"ai-generated-{uuid.uuid4()}", # Unique identifier for generated
            original_text="Generated by AI Brainstorming",
            score=evaluation.get("score"),
            target_audience=evaluation.get("target_audience", ""),
            status="pending"
        )
        session.add(new_idea)
        session.commit()
        session.refresh(new_idea)
        return new_idea
    
    raise HTTPException(status_code=500, detail="Failed to generate a random idea.")
